name: Staging Deploy

on:
  push:
    branches:
      - stage

jobs:
  check-backend-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: prod
        filters: |
          backend:
            - 'functions/**'
            - 'terraform/**'
            - 'workflows/**'

  build-static-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/landing
    - run: npm run build
      working-directory: frontend/landing
    - run: rsync -a static/ public/
      working-directory: frontend
    - uses: actions/upload-artifact@v2
      with:
        name: public
        path: frontend/public

  build-dashboard-stage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/dashboard
    - run: npm run build-stage
      working-directory: frontend/dashboard
    - uses: actions/upload-artifact@v2
      with:
        name: dashboard-stage
        path: frontend/public/dashboard

  build-editor-stage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/editor

    - run: npm run build-stage
      working-directory: frontend/editor
    - uses: actions/upload-artifact@v2
      with:
        name: editor-stage
        path: frontend/public/editor

    - run: npm run build-stage-demo
      working-directory: frontend/editor
    - uses: actions/upload-artifact@v2
      with:
        name: demo-stage
        path: frontend/public/demo

  synth-workflows:
    needs: [check-backend-changes]
    if: ${{ needs.check-backend-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: workflows
    - run: npm run synth
      working-directory: workflows
    - uses: actions/upload-artifact@v2
      with:
        name: workflows
        path: workflows/synth

  build-utils:
    needs: [check-backend-changes]
    if: ${{ needs.check-backend-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i -g dry-dry
    - run: dry ci
      working-directory: functions/utils
    - run: dry run build --dry-keep-package-json
      working-directory: functions/utils
    - uses: actions/upload-artifact@v2
      with:
        name: utils
        path: |
          functions/utils/dist
          functions/utils/package.json
          functions/utils/package-lock.json

  build-functions:
    needs: [build-utils, check-backend-changes]
    if: ${{ needs.check-backend-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        functionName:
          - adjust
          - align
          - align_worker
          - charge_credit
          - create_checkout
          - delete_transcript_files
          - fetch
          - get_metadata
          - payment
          - signup
          - transcode_envelope
          - transcode_transcription
          - transcode_playback
          - transcribe
          - transcription_watcher
          - upload
          - upload_watcher

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/download-artifact@v2
      with:
        name: utils
        path: functions/utils
    - run: npm i -g dry-dry
    - run: dry i
      working-directory: functions/${{ matrix.functionName }}
    - run: dry run build --dry-keep-package-json
      working-directory: functions/${{ matrix.functionName }}
    - run: cp -r ${{ matrix.functionName }} master/code
      working-directory: functions
    - run: cp -r utils master/utils
      working-directory: functions
    - run: npm i
      working-directory: functions/master
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.functionName }}
        path: |
          functions/master/code/dist
          functions/master/code/package.json
          functions/master/code/package-lock.json
          functions/master/utils/dist
          functions/master/utils/package.json
          functions/master/utils/package-lock.json
          functions/master/index.js
          functions/master/package.json

  push-git-prod:
    if: ${{ !failure() }}
    needs: [build-static-frontend, build-dashboard-stage, build-editor-stage, build-functions, synth-workflows]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout origin/prod
        git merge --squash stage
        git commit --no-edit
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: stage-deployed-frontend
