name: Staging Deploy

on:
  push:
    branches:
      - stage

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: prod
        filters: |
          backend:
            - 'functions/**'
            - 'terraform/**'
            - 'workflows/**'
          frontend:
            - 'frontend/**'




  build-static-frontend:
    needs: [changes]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/landing
    - run: npm run build
      working-directory: frontend/landing
    - run: rsync -a static/ public/
      working-directory: frontend
    - uses: actions/upload-artifact@v2
      with:
        name: public
        path: frontend/public

  build-dashboard:
    needs: [changes]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/dashboard
    - run: npm run build-stage
      working-directory: frontend/dashboard
    - uses: actions/upload-artifact@v2
      with:
        name: dashboard
        path: frontend/public/dashboard

  build-editor:
    needs: [changes]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/editor

    - run: npm run build-stage
      working-directory: frontend/editor
    - uses: actions/upload-artifact@v2
      with:
        name: editor
        path: frontend/public/editor

    - run: npm run build-stage-demo
      working-directory: frontend/editor
    - uses: actions/upload-artifact@v2
      with:
        name: demo
        path: frontend/public/demo

  deploy-frontend:
    needs: [changes, build-static-frontend, build-dashboard, build-editor]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan stage-deployed-frontend
        git reset --hard
    - uses: actions/download-artifact@v2
      with:
        name: public
        path: .
    - uses: actions/download-artifact@v2
      with:
        name: editor
        path: editor
    - uses: actions/download-artifact@v2
      with:
        name: demo
        path: demo
    - uses: actions/download-artifact@v2
      with:
        name: dashboard
        path: dashboard
    - run: |
        git add .
        git commit -m "Update hosted version"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: stage-deployed-frontend




  synth-workflows:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: workflows
    - run: npm run synth
      working-directory: workflows
    - uses: actions/upload-artifact@v2
      with:
        name: workflows
        path: workflows/synth

  build-utils:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i -g dry-dry
    - run: dry ci
      working-directory: functions/utils
    - run: dry run build --dry-keep-package-json
      working-directory: functions/utils
    - uses: actions/upload-artifact@v2
      with:
        name: utils
        path: |
          functions/utils/dist
          functions/utils/package.json
          functions/utils/package-lock.json

  build-functions:
    needs: [changes, build-utils]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        functionName:
          - adjust
          - align
          - align_worker
          - charge_credit
          - create_checkout
          - delete_transcript_files
          - fetch
          - get_metadata
          - payment
          - signup
          - transcode_envelope
          - transcode_transcription
          - transcode_playback
          - transcribe
          - transcription_watcher
          - upload
          - upload_watcher

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/download-artifact@v2
      with:
        name: utils
        path: functions/utils
    - run: npm i -g dry-dry
    - run: dry i
      working-directory: functions/${{ matrix.functionName }}
    - run: dry run build --dry-keep-package-json
      working-directory: functions/${{ matrix.functionName }}
    - run: cp -r ${{ matrix.functionName }} master/code
      working-directory: functions
    - run: cp -r utils master/utils
      working-directory: functions
    - run: npm i
      working-directory: functions/master
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.functionName }}
        path: |
          functions/master/code/dist
          functions/master/code/package.json
          functions/master/code/package-lock.json
          functions/master/utils/dist
          functions/master/utils/package.json
          functions/master/utils/package-lock.json
          functions/master/index.js
          functions/master/package.json

  deploy-backend:
    needs: [changes, build-functions, synth-workflows]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    environment: stage

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        path: terraform/functions
    - uses: hashicorp/setup-terraform@v1
    - run: terraform init && terraform apply -auto-approve
      working-directory: terraform/stage
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}




  test:
    if: ${{ !failure() && (needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true') }}
    needs: [changes, deploy-frontend, deploy-backend]
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: stage-deployed-frontend
          path: frontend/smoketest/public
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i && npm test
        working-directory: frontend/smoketest




  push-git-prod:
    if: ${{ !failure() }}
    needs: [test]
    runs-on: ubuntu-latest
    environment: approval

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: "prod"
        token: ${{ secrets.STEVEN_PAT }}
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git merge origin/stage
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.STEVEN_PAT }}
        force: true
        branch: prod
